language: android
jdk: oraclejdk8
sudo: false
before_install:
  - yes | sdkmanager "platforms;android-28"
android:
    components:
        - tools
        - build-tools-27.0.3
        - android-28
        - extra-android-m2repository
        - platform-tools
script:
    - cd opacclient
    - ./gradlew checkDebug lintDebug test jacocoRootReport coveralls
    - cat opacapp/build/reports/lint-results-debug.xml
cache:
    directories:
        - $HOME/.gradle
